const fs = require('fs');
const path = require('path');
const { google } = require('googleapis');

const API_KEY = 'AIzaSyCUix7tjuXlHuFosBF9zGD4_WFhCF2N0z0';
const CHANNEL_ID = 'UCAg6aehogJOmW6AORABxmKw';

const youtube = google.youtube({
  version: 'v3',
  auth: API_KEY,
});

let nextPageToken = null;

// === Generate blank index.html at start ===
const indexPath = path.join(__dirname, 'index.html');
const htmlContent = `<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><title>Blank Page</title></head>
<body>
  <h1>This is a blank page generated by live.js</h1>
</body>
</html>`;

try {
  fs.writeFileSync(indexPath, htmlContent, { encoding: 'utf8' });
  console.log('index.html generated successfully.');
} catch (err) {
  console.error('Error generating index.html:', err);
}

// === Your existing live chat code ===

async function getLiveChatId() {
  try {
    const searchResponse = await youtube.search.list({
      part: 'id,snippet',
      channelId: CHANNEL_ID,
      eventType: 'live',
      type: 'video',
      maxResults: 5,
      order: 'date',
    });

    if (searchResponse.data.items.length === 0) {
      console.log("No active live streams found.");
      return null;
    }

    const mostRecentLiveVideo = searchResponse.data.items[0];
    const liveVideoId = mostRecentLiveVideo.id.videoId;

    const videoDetailsResponse = await youtube.videos.list({
      part: 'liveStreamingDetails',
      id: liveVideoId,
    });

    const liveChatId = videoDetailsResponse.data.items[0].liveStreamingDetails.activeLiveChatId;
    console.log(`Found liveChatId: ${liveChatId}`);
    return liveChatId;
  } catch (error) {
    console.error("Error fetching liveChatId:", error);
    return null;
  }
}

async function pollLiveChat(liveChatId) {
  try {
    const response = await youtube.liveChatMessages.list({
      liveChatId,
      part: 'snippet,authorDetails',
      pageToken: nextPageToken,
      maxResults: 200,
    });

    nextPageToken = response.data.nextPageToken;

    const messages = response.data.items;
    messages.forEach(msg => {
      const author = msg.authorDetails.displayName;
      const message = msg.snippet.displayMessage;
      console.log(`${author}: ${message}`);
    });
  } catch (error) {
    console.error('Error fetching live chat messages:', error);
  }
}

async function main() {
  const liveChatId = await getLiveChatId();
  if (!liveChatId) return;

  setInterval(() => pollLiveChat(liveChatId), 500);
}

main();
